name: Cloudflare
on:
    push:

jobs:
    build-site:
        runs-on: ubuntu-latest
        name: Build static site
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v12
              with:
                  name: moosingin3space
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - run: nix-shell --run "script/build-static-site.sh"
            - uses: actions/upload-artifact@v2
              with:
                  name: out
                  path: client/public
    deploy-beta:
        needs: build-site
        if: github.ref == 'refs/heads/beta'
        runs-on: ubuntu-latest
        name: Deploy Beta Cloudflare Worker
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/download-artifact@v2
              with:
                  name: out
                  path: client/public
            - name: Deploy
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  environment: 'beta'
              env:
                  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
                  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
    deploy-prod:
        needs: build-site
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        name: Deploy Production Cloudflare Worker
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/download-artifact@v2
              with:
                  name: out
                  path: client/public
            - name: Deploy
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  environment: 'production'
              env:
                  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
                  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
