name: Cloudflare Beta
on:
    push:
        branches:
            - beta

jobs:
    build:
        runs-on: ubuntu-latest
        name: Deploy Beta Cloudflare Worker
        steps:
            - uses: actions/checkout@v2.0.0
            - name: Deploy
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  environment: 'beta'
              env:
                  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
                  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
